Global:
  use_gpu: true
  epoch_num: 50
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: C:/Users/sharj/Desktop/Rumsey_Map_OCR/PaddleOCR/output/rec_finetune
  save_epoch_step: 10
  eval_batch_step: [0, 500]
  cal_metric_during_train: true
  pretrained_model: C:/Users/sharj/Desktop/Rumsey_Map_OCR/PaddleOCR/pretrain_models/en_PP-OCRv4_rec_train/student
  
  # ðŸ‘‡ THIS IS THE CHANGE: Points to your latest checkpoint to auto-resume
  checkpoints: C:/Users/sharj/Desktop/Rumsey_Map_OCR/PaddleOCR/output/rec_finetune/latest
  
  save_inference_dir: null
  use_visualdl: false
  infer_img: null
  character_dict_path: C:/Users/sharj/Desktop/Rumsey_Map_OCR/PaddleOCR_Engine/ppocr/utils/en_dict.txt
  max_text_length: 25
  infer_mode: false
  use_space_char: true
  distributed: false 
  save_res_path: C:/Users/sharj/Desktop/Rumsey_Map_OCR/PaddleOCR/output/rec/predicts_ppocrv4.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0001
    warmup_epoch: 5
  regularizer:
    name: 'L2'
    factor: 0.00001

Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform:
  Backbone:
    name: PPLCNetV3
    scale: 0.95
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 120
            depth: 2
            hidden_dims: 120
            use_guide: True
          Head:
            fc_decay: 0.00001

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: C:/Users/sharj/Desktop/Rumsey_Map_OCR/PaddleOCR/train_data
    ext_op_transform_idx: 1
    label_file_list:
    - C:/Users/sharj/Desktop/Rumsey_Map_OCR/PaddleOCR/train_data/rec_gt_train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecAug:
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys: ['image', 'label_ctc', 'valid_ratio', 'length']
  loader:
    shuffle: true
    batch_size_per_card: 64
    drop_last: true
    num_workers: 0

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: C:/Users/sharj/Desktop/Rumsey_Map_OCR/PaddleOCR/train_data
    label_file_list:
    - C:/Users/sharj/Desktop/Rumsey_Map_OCR/PaddleOCR/train_data/rec_gt_val.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys: ['image', 'label_ctc', 'valid_ratio', 'length']
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 64
    num_workers: 0